/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#undef BUILD_DEBUG

#define DEFAULT_BIT_RATE 8000000

#define DEFAULT_LOCAL_PORT 27183

#define DEFAULT_MAX_SIZE 0

#define HIDPI_SUPPORT

#define SCRCPY_VERSION "1.6"

#define SKIP_FRAMES

#define WINDOWS_NOCONSOLE

