/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#undef BUILD_DEBUG

#define DEFAULT_BIT_RATE 8000000

#define DEFAULT_IP_ADDRESS 0x7F000001

#define USB_IP_ADDRESS 0xC0A82A81 // 192.168.42.129

#define DEFAULT_LOCAL_PORT 27183

#define DEFAULT_MAX_SIZE 0

#define HIDPI_SUPPORT

#define SCRCPY_VERSION "1.6"

#define SKIP_FRAMES

#define WINDOWS_NOCONSOLE

